apiVersion: v1
kind: Namespace
metadata:
  name: roadpricing
  labels:
    name: roadpricing
---
apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  namespace: roadpricing
  labels:
    app: pricing-service
    tier: backend
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: pricing-service
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
  namespace: roadpricing
spec:
  selector:
    matchLabels:
      app: pricing-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: pricing-service
        tier: backend
    spec:
      containers:
        - name: pricing-service
          image: ghcr.io/roadpricing-s6-group3/pricing-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
