apiVersion: v1
kind: Namespace
metadata:
  name: roadpricing
  labels:
    name: roadpricing
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: roadpricing
  labels:
    app: vehicle-service
    tier: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: vehicle-service
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: roadpricing
spec:
  selector:
    matchLabels:
      app: vehicle-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicle-service
        tier: backend
    spec:
      containers:
        - name: vehicle-service
          image: ghcr.io/roadpricing-s6-group3/vehicle-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080