apiVersion: v1
kind: Namespace
metadata:
  name: roadpricing
  labels:
    name: roadpricing
---
apiVersion: v1
kind: Service
metadata:
  name: traveldata-db
  namespace: roadpricing
  labels:
    app: traveldata-db
    tier: backend
spec:
  selector:
    app: traveldata-db
  ports:
    - protocol: TCP
      name: "3308"
      port: 3308
      targetPort: 3308
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveldata-db
  namespace: roadpricing
spec:
  selector:
    matchLabels:
      app: traveldata-db
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: traveldata-db
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3308
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Teun
            - name: MYSQL_TCP_PORT
              value: "3308"
            - name: MYSQL_DATABASE
              value: traveldata
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: roadpricing
  labels:
    app: user-db
    tier: backend
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      name: "3307"
      port: 3307
      targetPort: 3307
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: roadpricing
spec:
  selector:
    matchLabels:
      app: user-db
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-db
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3307
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Teun
            - name: MYSQL_TCP_PORT
              value: "3307"
            - name: MYSQL_DATABASE
              value: user
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-db
  namespace: roadpricing
  labels:
    app: vehicle-db
    tier: backend
spec:
  selector:
    app: vehicle-db
  ports:
    - protocol: TCP
      name: "3306"
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-db
  namespace: roadpricing
spec:
  selector:
    matchLabels:
      app: vehicle-db
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicle-db
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Teun
            - name: MYSQL_TCP_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: vehicle
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roadpricing
  labels:
    app: mongodb
    tier: backend
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      name: "27017"
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roadpricing
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: backend
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: Root
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-db
  namespace: roadpricing
  labels:
    app: invoice-db
    tier: backend
spec:
  selector:
    app: invoice-db
  ports:
    - protocol: TCP
      name: "3309"
      port: 3309
      targetPort: 3309
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-db
  namespace: roadpricing
spec:
  selector:
    matchLabels:
      app: invoice-db
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: invoice-db
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3309
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Teun
            - name: MYSQL_TCP_PORT
              value: "3309"
            - name: MYSQL_DATABASE
              value: invoice