apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: traveldata-mysql
  name: traveldata-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traveldata-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-net: "true"
        io.kompose.service: traveldata-mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: traveldata
            - name: MYSQL_ROOT_PASSWORD
              value: Teun
            - name: MYSQL_TCP_PORT
              value: "3308"
          image: mysql:latest
          name: traveldata-db
          ports:
            - containerPort: 3308
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: traveldatadata
            - mountPath: /etc/mysql/conf.d
              name: traveldatadata
      restartPolicy: Always
      volumes:
        - name: traveldatadata
          persistentVolumeClaim:
            claimName: traveldatadata
        - name: traveldatadata
          persistentVolumeClaim:
            claimName: traveldatadata
status: {}
