apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: traveldata-mysql
  name: traveldata-mysql
spec:
  ports:
    - name: "3308"
      port: 3308
      targetPort: 3308
  selector:
    io.kompose.service: traveldata-mysql
status:
  loadBalancer: {}
