apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: vehicle-mysql
  name: vehicle-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vehicle-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-net: "true"
        io.kompose.service: vehicle-mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: vehicle
            - name: MYSQL_ROOT_PASSWORD
              value: Teun
          image: mysql:latest
          name: vehicle-db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vehicledata
            - mountPath: /etc/mysql/conf.d
              name: vehicledata
      restartPolicy: Always
      volumes:
        - name: vehicledata
          persistentVolumeClaim:
            claimName: vehicledata
        - name: vehicledata
          persistentVolumeClaim:
            claimName: vehicledata
status: {}
