apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service-deployment
  labels:
    app: invoice-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
        - name: autopilot-cluster-1
          image: gcr.io/graphic-matrix-308512/invoice-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: invoice-service-network
  namespace: "default"
spec:
  selector:
    app: invoice-service
  ports:
    # The port that this service listens to for incoming traffic.
    - port: 8083
      # The port that this service sends requests to.
      targetPort: 8083
  #  LoadBalancer to expose the service externally,
  #  NodePort to expose the service on a port across each of your nodes,
  #  and ClusterIP to expose the service on a cluster-internal IP
  type: ClusterIP
