version: '3.8'
services:
  vehicle-service:
    container_name: vehicle-service
    build:
      context: vehicle-service/
      dockerfile: Dockerfile
    networks:
      - spring-net
    restart: "no"
    depends_on:
      - roadpricing-mysql
    image: vehicle-service:latest
    ports:
      - 8080:8080

  user-service:
    container_name: user-service
    build:
      context: user-service/
      dockerfile: Dockerfile
    networks:
      - spring-net
    restart: "no"
    depends_on:
      -  roadpricing-mysql
    image: user-service:latest
    ports:
      - 8084:8084

  invoice-service:
    container_name: invoice-service
    build:
      context: invoice-service/
      dockerfile: Dockerfile
    networks:
      - spring-net
    restart: "no"
    image: invoice-service:latest
    ports:
      - 8083:8083

  traveldata-service:
    container_name: traveldata-service
    build:
      context: traveldata-service/
      dockerfile: Dockerfile
    networks:
      - spring-net
    restart: "no"
    depends_on:
      - roadpricing-mysql
    image: traveldata-service:latest
    ports:
      - 8085:8085

  roadpricing-mysql:
    container_name: roadpricing-DB
    image: mysql:latest
    ports:
      - 3306:3306
    networks:
      - spring-net
    environment:
      - MYSQL_ROOT_PASSWORD=Teun
      - MYSQL_DATABASE=vehicle
    volumes:
      - vehicledata:/var/lib/mysql
      - vehicledata:/etc/mysql/conf.d
      - userdata:/var/lib/mysql
      - userdata:/etc/mysql/conf.d


networks:
  spring-net:
    name: spring-net
    driver: bridge

volumes:
  vehicledata:
  userdata:
