  name: build & test
  on:
    push:
      - main
      - vehicle-service
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Build with Maven
          run: mvn -B package --file pom.xml


