  name: build services
  on:
    push:
      branches: [ main ]

  jobs:
    build-vehicle-service:
      name: Build vehicle service
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Cache Maven packages
            uses: actions/cache@v2
            with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
        - name: Build with Maven
          run: mvn -B package --file microservices/vehicle-service/pom.xml

    build-user-service:
      name: Build user service
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Cache Maven packages
          uses: actions/cache@v2
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
        - name: Build with Maven
          run: mvn -B package --file microservices/user-service/pom.xml

    build-invoice-service:
      name: Build invoice service
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Cache Maven packages
            uses: actions/cache@v2
            with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
        - name: Build with Maven
          run: mvn -B package --file microservices/invoice-service/pom.xml

    build-traveldata-service:
      name: Build traveldata service
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Cache Maven packages
            uses: actions/cache@v2
            with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
        - name: Build with Maven
          run: mvn -B package --file microservices/traveldata-service/pom.xml


