  name: build services and push img
  on:
    push:
      branches: [ main ]

  env:
    REGISTRY: ghcr.io

  jobs:
    build-vehicle-service:
      name: Build vehicle service
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'

      name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2   

        - name: Login To Registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{env.REGISTRY}}
            username: ${{github.actor}}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build with Maven
          run: mvn -B package --file microservices/vehicle-service/pom.xml

        - name: Cache Maven Package
          uses: actions/cache@v2
          with:
            path: target
            key: ${{ runner.os }}-maven-target-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-target-
              ${{ runner.os }}-maven-

        - name: Build & Push Vehicle-Service
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            file: ./microservices/vehicle-service/Dockerfile
            context: .
            push: true
            tags: ${{ env.REGISTRY }}/roadpricing-s6-group3/vehicle-service:latest

    build-user-service:
      name: Build user service
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'

      name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  

        - name: Build with Maven
          run: mvn -B package --file microservices/user-service/pom.xml
            
        - name: Login To Registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{env.REGISTRY}}
            username: ${{github.actor}}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build & Push User-Service
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            file: ./microservices/user-service/Dockerfile
            context: .
            push: true
            tags: ${{ env.REGISTRY }}/roadpricing-s6-group3/user-service:latest

    build-invoice-service:
      name: Build invoice service
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'

      name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  
            
        - name: Login To Registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{env.REGISTRY}}
            username: ${{github.actor}}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build with Maven
          run: mvn -B package --file microservices/invoice-service/pom.xml

        - name: Build & Push Invoice-Service
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            file: ./microservices/invoice-service/Dockerfile
            context: .
            push: true
            tags: ${{ env.REGISTRY }}/roadpricing-s6-group3/invoice-service:latest

    build-traveldata-service:
      name: Build traveldata service
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'

      name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  
            
        - name: Login To Registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{env.REGISTRY}}
            username: ${{github.actor}}
            password: ${{ secrets.GITHUB_TOKEN }}


        - name: Build with Maven
          run: mvn -B package --file microservices/traveldata-service/pom.xml

        - name: Build & Push TravelData-Service
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            file: ./microservices/traveldata-service/Dockerfile
            context: .
            push: true
            tags: ${{ env.REGISTRY }}/roadpricing-s6-group3/traveldata-service:latest



    # build-and-push-images:
    #   needs: [ build-vehicle-service ]
    #   name: build-and-push-images
    #   runs-on: self-hosted
    #   permissions:
    #     contents: read
    #     packages: write
      
    #   steps:
    #     - name: Checkout Repository
    #       uses: actions/checkout@v3

    #     - name: Login To Registry
    #       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #       with:
    #         registry: ${{env.REGISTRY}}
    #         username: ${{github.actor}}
    #         password: ${{ secrets.GITHUB_TOKEN }}

    #     - name: Build & Push Vehicle-Service
    #       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #       with:
    #         file: ./microservices/vehicle-service/Dockerfile
    #         context: .
    #         push: true
    #         tags: ${{ env.REGISTRY }}/roadpricing-s6-group3/vehicle-service:latest


