name: build vehicle-service
on:
  push:
    branches: [ Vehicle-Service ]

jobs:
  build-vehicle-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file microservices/vehicle-service/pom.xml
